export interface DairyEstablishment {
  regNo: number
  name: string
  adba: string | null
  telephone: string
  streetAddr: string
  city: string
  province: string
  postalCode: string
}

export const DairyEstablishmentList: DairyEstablishment[] = [
  {
    regNo: 37,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(613) 774-2310',
    streetAddr: '490 GORDON STREET',
    city: 'WINCHESTER',
    province: 'ON',
    postalCode: 'K0C 2K0',
  },
  {
    regNo: 44,
    name: 'KRAFT HEINZ CANADA ULC',
    adba: null,
    telephone: '(613) 537-8001',
    streetAddr: '70 DICKINSON DR.',
    city: 'INGLESIDE',
    province: 'ON',
    postalCode: 'K0C 1MO',
  },
  {
    regNo: 62,
    name: 'GRIFFITH FOODS LIMITED',
    adba: null,
    telephone: '(416) 288-5655',
    streetAddr: '757 PHARMACY AVE.',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M1L 3J8',
  },
  {
    regNo: 76,
    name: 'BRIGHT CHEESE & BUTTER MANUFACTURING COMPANY LIMITED',
    adba: null,
    telephone: '(519) 454-4810',
    streetAddr: '816503 County Rd. #22',
    city: 'BRIGHT',
    province: 'ON',
    postalCode: 'N0J 1B0',
  },
  {
    regNo: 86,
    name: 'GAY LEA FOODS CO-OPERATIVE LIMITED',
    adba: null,
    telephone: '(519) 392-6864',
    streetAddr: '21 CLINTON STREET',
    city: 'TEESWATER',
    province: 'ON',
    postalCode: 'N0G 2S0',
  },
  {
    regNo: 92,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(519) 348-8414',
    streetAddr: '100 ST. GEORGE STREET',
    city: 'MITCHELL',
    province: 'ON',
    postalCode: 'N0K 1N0',
  },
  {
    regNo: 215,
    name: 'OAK GROVE CHEESE FACTORY LIMITED',
    adba: null,
    telephone: '(519) 662-2539',
    streetAddr: '29 BLEAMS ROAD EAST',
    city: 'HAMBURG',
    province: 'ON',
    postalCode: 'N3A 1G6',
  },
  {
    regNo: 277,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(905) 641-8151',
    streetAddr: '461 STEWART ROAD',
    city: 'NIAGARA ON THE LAKE',
    province: 'ON',
    postalCode: 'L0S 1J0',
  },
  {
    regNo: 441,
    name: 'GAY LEA FOODS CO-OPERATIVE LIMITED',
    adba: null,
    telephone: '(647) 277-4320',
    streetAddr: '100 CLAYSON ROAD',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M9M 2G7',
  },
  {
    regNo: 511,
    name: 'SAPUTO DAIRY PRODUCTS CANADA G.P.',
    adba: null,
    telephone: '(519) 655-2337',
    streetAddr: '284 HOPE STREET WEST',
    city: 'TAVISTOCK',
    province: 'ON',
    postalCode: 'N0B 2R0',
  },
  {
    regNo: 512,
    name: 'THE STIRLING CREAMERY LIMITED',
    adba: null,
    telephone: '(905) 283-5220',
    streetAddr: '1 FRONT STREET',
    city: 'STIRLING',
    province: 'ON',
    postalCode: 'K0K 3E0',
  },
  {
    regNo: 524,
    name: 'GAY LEA FOODS CO-OPERATIVE LIMITED',
    adba: null,
    telephone: '(519) 822-5530',
    streetAddr: '21 SPEEDVALE AVENUE WEST',
    city: 'GUELPH',
    province: 'ON',
    postalCode: 'N1H 1J5',
  },
  {
    regNo: 541,
    name: 'THE ALLISTON CREAMERY & DAIRY LIMITED',
    adba: null,
    telephone: '(705) 435-6751',
    streetAddr: '26 DOMINION STREET',
    city: 'ALLISTON',
    province: 'ON',
    postalCode: 'L9R 1L5',
  },
  {
    regNo: 578,
    name: 'PINE RIVER CHEESE AND BUTTER COOPERATIVE',
    adba: null,
    telephone: '(519) 395-2638',
    streetAddr: 'LOT 36, CON. 6, HURON TOWNSHIP, 635 HIGHWAY',
    city: 'RIPLEY',
    province: 'ON',
    postalCode: 'N0G 2R0',
  },
  {
    regNo: 585,
    name: 'A.M. JENSEN LIMITED',
    adba: 'WILTON CHEESE FACTORY',
    telephone: '(613) 386-7314',
    streetAddr: '287 Simmons Road',
    city: 'ODESSA',
    province: 'ON',
    postalCode: 'K0H 2H0',
  },
  {
    regNo: 743,
    name: 'LA FROMAGERIE COOPERATIVE ST-ALBERT INC. ET ST. ALBERT CHEESE CO-OPERATIVE INC.',
    adba: 'FROMAGERIE ST. ALBERT/ST. ALBERT',
    telephone: '(613) 987-2172',
    streetAddr: '150 ST. PAUL P.O. BOX 30 Lot 19, Concession 10',
    city: 'ST. ALBERT',
    province: 'ON',
    postalCode: 'K0A 3C0',
  },
  {
    regNo: 839,
    name: 'ARLA FOODS INC.',
    adba: null,
    telephone: '(519) 356-2271',
    streetAddr: '7412 ROAD 164',
    city: 'ATWOOD',
    province: 'ON',
    postalCode: 'N0G 1B0',
  },
  {
    regNo: 913,
    name: 'HENRY FOOD INC.',
    adba: 'MAPLE DALE CHEESE',
    telephone: '(613) 477-2454',
    streetAddr: '2864 HIGHWAY 37 NORTH',
    city: 'PLAINFIELD',
    province: 'ON',
    postalCode: 'K0K 2V0',
  },
  {
    regNo: 961,
    name: 'GAY LEA FOODS CO-OPERATIVE LIMITED',
    adba: 'IVANHOE CHEESE',
    telephone: '(613) 473-4269',
    streetAddr: 'R.R. #5, 11301 HWY. 62 NORTH',
    city: 'MADOC',
    province: 'ON',
    postalCode: 'K0K 2K0',
  },
  {
    regNo: 970,
    name: 'EMPIRE CHEESE CO-OPERATIVE',
    adba: null,
    telephone: '(705) 653-3187',
    streetAddr: 'R.R. #5, 1120 COUNTY RD. #8',
    city: 'CAMPBELLFORD',
    province: 'ON',
    postalCode: 'K0L 1L0',
  },
  {
    regNo: 1003,
    name: 'GELATO FRESCO INC',
    adba: null,
    telephone: '(416) 785-5415',
    streetAddr: '60 TYCOS DRIVE',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M6B 1V9',
  },
  {
    regNo: 1004,
    name: 'YA YA FOODS CORP.',
    adba: null,
    telephone: '(416) 677-5926',
    streetAddr: '450 KIPLING AVENUE',
    city: 'ETOBICOKE',
    province: 'ON',
    postalCode: 'M8Z 5E1',
  },
  {
    regNo: 1006,
    name: 'HANS DAIRY INC.',
    adba: null,
    telephone: '(905) 671-3200',
    streetAddr: '3400 AMERICAN DRIVE',
    city: 'MISSISSAUGA',
    province: 'ON',
    postalCode: 'L4V 1C1',
  },
  {
    regNo: 1018,
    name: 'MARIPOSA DAIRY LTD.',
    adba: null,
    telephone: '(705) 324-9306',
    streetAddr: '201 St. George Street',
    city: 'LINDSAY',
    province: 'ON',
    postalCode: 'K9V 5Z9',
  },
  {
    regNo: 1019,
    name: 'MARIPOSA DAIRY LTD.',
    adba: null,
    telephone: '(705) 324-9306',
    streetAddr: '163 ST. DAVID STREET UNIT 1',
    city: 'LINDSAY',
    province: 'ON',
    postalCode: 'K9V 4Z6',
  },
  {
    regNo: 1021,
    name: 'GRANDE CHEESE COMPANY LIMITED',
    adba: null,
    telephone: '(905) 856-6880',
    streetAddr: '468 JEVLAN DRIVE',
    city: 'WOODBRIDGE',
    province: 'ON',
    postalCode: 'L4L 8L4',
  },
  {
    regNo: 1023,
    name: "DAVID CHAPMAN'S ICE CREAM LIMITED",
    adba: "CHAPMAN'S ICE CREAM",
    telephone: '(519) 986-3131',
    streetAddr: "100 CHAPMAN'S CRESCENT",
    city: 'MARKDALE',
    province: 'ON',
    postalCode: 'N0C 1H0',
  },
  {
    regNo: 1024,
    name: "DAVID CHAPMAN'S ICE CREAM LIMITED",
    adba: "CHAPMAN'S ICE CREAM",
    telephone: '(519) 986-3131',
    streetAddr: "200 CHAPMAN'S CRESCENT",
    city: 'MARKDALE',
    province: 'ON',
    postalCode: 'N0C 1H0',
  },
  {
    regNo: 1028,
    name: 'SAUGEEN COUNTRY DAIRY LTD',
    adba: null,
    telephone: '(519) 369-5836',
    streetAddr: 'RR 1 423809 CONCESSION 6 LOT 8, CONCESSION 7',
    city: 'MARKDALE',
    province: 'ON',
    postalCode: 'N0C 1H0',
  },
  {
    regNo: 1029,
    name: 'WILMA MOL',
    adba: 'SLATE RIVER DAIRY',
    telephone: '(807) 577-6455',
    streetAddr: '8 HIGHWAY 608',
    city: 'NEEBING',
    province: 'ON',
    postalCode: 'P7L 0C6',
  },
  {
    regNo: 1031,
    name: '1279089 ONTARIO LTD.',
    adba: 'LONDON ICE CREAM COMPANY',
    telephone: '(519) 673-2783',
    streetAddr: '43 BASELINE ROAD WEST',
    city: 'LONDON',
    province: 'ON',
    postalCode: 'N6J 1V5',
  },
  {
    regNo: 1035,
    name: 'TRIPLE "A" CHEESE COMPANY LTD.',
    adba: null,
    telephone: '(905) 678-7053',
    streetAddr: '7210 TORBRAM ROAD',
    city: 'MISSISSAUGA',
    province: 'ON',
    postalCode: 'L4T 3L7',
  },
  {
    regNo: 1036,
    name: 'ELITE DAIRY LTD.',
    adba: null,
    telephone: '(416) 767-4574',
    streetAddr: '123 MCCORMACK STREET',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M6N 1X8',
  },
  {
    regNo: 1041,
    name: 'LINSEY FOODS LTD.',
    adba: null,
    telephone: '(905) 940-3850',
    streetAddr: '121 McPherson Street',
    city: 'MARKHAM',
    province: 'ON',
    postalCode: 'L3R 3L3',
  },
  {
    regNo: 1045,
    name: 'MAPLETON ORGANIC DAIRY INC.',
    adba: null,
    telephone: '(519) 638-1115',
    streetAddr: '8548 Wellington Road 7',
    city: 'Moorefield',
    province: 'ON',
    postalCode: 'N0G 2K0',
  },
  {
    regNo: 1157,
    name: 'MILDMAY CREAMERY LTD.',
    adba: null,
    telephone: '(519) 367-2678',
    streetAddr: '73 ELORA STREET',
    city: 'MILDMAY',
    province: 'ON',
    postalCode: 'N0G 2J0',
  },
  {
    regNo: 1165,
    name: 'SAPUTO DAIRY PRODUCTS CANADA GP',
    adba: null,
    telephone: '(613) 392-6762',
    streetAddr: '7 RIVERSIDE DR.',
    city: 'TRENTON',
    province: 'ON',
    postalCode: 'K8V 5R7',
  },
  {
    regNo: 1290,
    name: 'THORNLOE INC. (THORNLOE CHEESE)',
    adba: 'Thornloe Cheese',
    telephone: '(705) 647-7441',
    streetAddr: 'R.R.#2, HWY 11 NORTH',
    city: 'THORNLOE',
    province: 'ON',
    postalCode: 'P0J 1S0',
  },
  {
    regNo: 1400,
    name: 'ARLA FOODS INC.',
    adba: null,
    telephone: '(905) 669-9393',
    streetAddr: '675 RIVERMEDE ROAD',
    city: 'CONCORD',
    province: 'ON',
    postalCode: 'L4K 2G9',
  },
  {
    regNo: 1401,
    name: 'GRANDE CHEESE COMPANY LIMITED',
    adba: null,
    telephone: '(905) 856-6880',
    streetAddr: '175 MILVAN DRIVE',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M9L 1Z8',
  },
  {
    regNo: 1402,
    name: 'INTERNATIONAL CHEESE CO. LTD.',
    adba: null,
    telephone: '(416) 769-3547',
    streetAddr: '67 MULOCK AVENUE',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M6N 3C5',
  },
  {
    regNo: 1403,
    name: 'PORTUGUESE CHEESE COMPANY LIMITED',
    adba: 'PORTUGUESE CHEESE COMPANY',
    telephone: '(416) 259-4349',
    streetAddr: '2 BUCKINGHAM STREET',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M8Y 2W1',
  },
  {
    regNo: 1404,
    name: 'QUALITY CHEESE INC.',
    adba: null,
    telephone: '(905) 265-9991',
    streetAddr: '111 JEVLAN DRIVE',
    city: 'VAUGHAN',
    province: 'ON',
    postalCode: 'L4L 8C2',
  },
  {
    regNo: 1405,
    name: 'SILANI SWEET CHEESE LTD.',
    adba: null,
    telephone: '(905) 939-2519',
    streetAddr: '4205 2ND LINE',
    city: 'SCHOMBERG',
    province: 'ON',
    postalCode: 'L0G 1T0',
  },
  {
    regNo: 1406,
    name: 'QUALITY CHEESE INC.',
    adba: null,
    telephone: '(905) 265-9991',
    streetAddr: '210 CREDITVIEW',
    city: 'VAUGHAN',
    province: 'ON',
    postalCode: 'L4L 9N4',
  },
  {
    regNo: 1409,
    name: 'ROMAN CHEESE PRODUCTS LIMITED',
    adba: null,
    telephone: '(905) 356-2639',
    streetAddr: '4916 MONTROSE ROAD',
    city: 'NIAGARA FALLS',
    province: 'ON',
    postalCode: 'L2H 1K5',
  },
  {
    regNo: 1410,
    name: 'GAY LEA FOODS CO-OPERATIVE LIMITED',
    adba: 'SALERNO',
    telephone: '(905) 544-6281',
    streetAddr: '20 MORLEY STREET',
    city: 'HAMILTON',
    province: 'ON',
    postalCode: 'L8H 3R7',
  },
  {
    regNo: 1411,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(613) 969-2188',
    streetAddr: '184 BLACK DIAMOND ROAD',
    city: 'BELLEVILLE',
    province: 'ON',
    postalCode: 'K8N 5A1',
  },
  {
    regNo: 1414,
    name: 'GALATI CHEESE COMPANY LIMITED',
    adba: null,
    telephone: '(519) 973-7510',
    streetAddr: '931 TECUMSEH ROAD WEST',
    city: 'WINDSOR',
    province: 'ON',
    postalCode: 'N8X 2A9',
  },
  {
    regNo: 1422,
    name: 'UNILEVER CANADA INC',
    adba: 'GOOD HUMOR - BREYERS',
    telephone: '(226) 931-2541',
    streetAddr: '175 UNION STREET',
    city: 'SIMCOE',
    province: 'ON',
    postalCode: 'N0E 1H0',
  },
  {
    regNo: 1425,
    name: 'ORGANIC MEADOW LIMITED PARTNERSHIP',
    adba: null,
    telephone: '(519) 767-9694',
    streetAddr: '362 Laird Road',
    city: 'Guelph',
    province: 'ON',
    postalCode: 'N1G 3X7',
  },
  {
    regNo: 1426,
    name: 'QUALITY CHEESE INC',
    adba: null,
    telephone: '(905) 265-9991',
    streetAddr: '40 Centennial Road',
    city: 'ORANGEVILLE',
    province: 'ON',
    postalCode: 'L9W 3T3',
  },
  {
    regNo: 1427,
    name: 'KAWARTHA DAIRY LIMITED',
    adba: null,
    telephone: '(705) 738-5123',
    streetAddr: '89 PRINCE ST. W.',
    city: 'BOBCAYGEON',
    province: 'ON',
    postalCode: 'K0M 1A0',
  },
  {
    regNo: 1429,
    name: 'FRASER SCATES  LTD / CENTRAL SMITH',
    adba: 'Central Smith',
    telephone: '(705) 742-5867',
    streetAddr: '739 LINDSAY HWY.',
    city: 'Selwyn',
    province: 'ON',
    postalCode: 'K9J 0C5',
  },
  {
    regNo: 1431,
    name: "HEWITT'S DAIRY LIMITED",
    adba: "HEWITT'S DAIRY BAR",
    telephone: '(905) 768-3524',
    streetAddr: '4210 HWY #6 NORTH',
    city: 'HAGERSVILLE',
    province: 'ON',
    postalCode: 'N0A 1H0',
  },
  {
    regNo: 1432,
    name: "HEWITT'S DAIRY LIMITED",
    adba: null,
    telephone: '(905) 768-3524',
    streetAddr: '128 KING STREET EAST',
    city: 'HAGERSVILLE',
    province: 'ON',
    postalCode: 'N0A 1H0',
  },
  {
    regNo: 1438,
    name: 'NESTLE CANADA INC.',
    adba: null,
    telephone: '(519) 686-0182',
    streetAddr: '980 WILTON GROVE ROAD',
    city: 'LONDON',
    province: 'ON',
    postalCode: 'N6A 6C5',
  },
  {
    regNo: 1439,
    name: '1467317 ONTARIO INC',
    adba: "SHAW'S ICE CREAM",
    telephone: '(519) 631-2510',
    streetAddr: '6598 SUNSET ROAD, RR#4',
    city: 'ST. THOMAS',
    province: 'ON',
    postalCode: 'N5P 3S8',
  },
  {
    regNo: 1440,
    name: 'UPPER CANADA CHEESE COMPANY INC.',
    adba: null,
    telephone: '(905) 562-9730',
    streetAddr: '4159 JORDAN ROAD',
    city: 'JORDON STATION',
    province: 'ON',
    postalCode: 'L0R 1P0',
  },
  {
    regNo: 1445,
    name: '1711602 ONTARIO LIMITED',
    adba: 'WHITE ROSE-SAY "CHEESE"',
    telephone: '(519) 227-1776',
    streetAddr: '34026 NEIL ROAD LOT 24, CONCESSION 2',
    city: 'LUCAN',
    province: 'ON',
    postalCode: 'N0M 2J0',
  },
  {
    regNo: 1452,
    name: '446816 ONTARIO INC',
    adba: "CENTRESIDE DAIRY '80",
    telephone: '(613) 432-2914',
    streetAddr: '61 LORNE STREET NORTH',
    city: 'RENFREW',
    province: 'ON',
    postalCode: 'K7V 1K8',
  },
  {
    regNo: 1457,
    name: 'ST. CLAIR ICE CREAM LIMITED',
    adba: null,
    telephone: '(416) 694-5811',
    streetAddr: '2861 DANFORTH AVENUE',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M4C 1M2',
  },
  {
    regNo: 1478,
    name: 'AGROPUR COOPÉRATIVE',
    adba: 'NATREL',
    telephone: '(416) 442-2349',
    streetAddr: '1275 LAWRENCE AVENUE EAST',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M3A 3P9',
  },
  {
    regNo: 1485,
    name: 'SAPUTO DAIRY PRODUCTS CANADA G.P.',
    adba: null,
    telephone: '(613) 761-7269',
    streetAddr: '861 CLYDE AVENUE',
    city: 'OTTAWA',
    province: 'ON',
    postalCode: 'K1Z 5A4',
  },
  {
    regNo: 1490,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(613) 834-5700',
    streetAddr: '1001 DAIRY DRIVE',
    city: 'OTTAWA',
    province: 'ON',
    postalCode: 'K4A 3N3',
  },
  {
    regNo: 1513,
    name: 'GAY LEA FOOD CO-OPERATIVE LTD.',
    adba: null,
    telephone: '(647) 277-4320',
    streetAddr: '180 ORMONT DRIVE',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M9L 1N7',
  },
  {
    regNo: 1517,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(705) 566-2010',
    streetAddr: '500 BARRYDOWNE ROAD',
    city: 'SUDBURY',
    province: 'ON',
    postalCode: 'P3A 3T3',
  },
  {
    regNo: 1519,
    name: "THE REID'S DAIRY COMPANY LTD.",
    adba: null,
    telephone: '(613) 967-1970',
    streetAddr: '222 BELL BOULEVARD',
    city: 'BELLEVILLE',
    province: 'ON',
    postalCode: 'K8N 5B6',
  },
  {
    regNo: 1530,
    name: 'WHITE DIAMONDS INC.',
    adba: null,
    telephone: '(905) 624-6026',
    streetAddr: '15-5484 TOMKEN ROAD',
    city: 'MISSISSAUGA',
    province: 'ON',
    postalCode: 'L4W 2Z6',
  },
  {
    regNo: 1536,
    name: 'EURO-BALKAN SPECIALTY FOODS',
    adba: null,
    telephone: '(905) 428-8192',
    streetAddr: '1621 MCEWEN ROAD UNIT 34',
    city: 'WHITBY',
    province: 'ON',
    postalCode: 'L1N 9A5',
  },
  {
    regNo: 1539,
    name: 'YOPLAIT LIBERTE CANADA CO.',
    adba: null,
    telephone: '(416) 661-0582',
    streetAddr: '60 BRISBANE ROAD',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M3J 2K2',
  },
  {
    regNo: 1542,
    name: 'M-C DAIRY COMPANY (1991) LIMITED',
    adba: null,
    telephone: '(416) 231-1491',
    streetAddr: '106 NORTH QUEEN STREET',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M8Z 2E2',
  },
  {
    regNo: 1543,
    name: 'MAX & LION PRODUCTION INC',
    adba: 'ELWEST CANADA',
    telephone: '(905) 840-6827',
    streetAddr: '12 FISHERMAN DRIVE, UNIT 3 & 4',
    city: 'BRAMPTON',
    province: 'ON',
    postalCode: 'L7A 1B6',
  },
  {
    regNo: 1545,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(416) 622-2811',
    streetAddr: '25 RAKELY COURT',
    city: 'ETOBICOKE',
    province: 'ON',
    postalCode: 'M9C 5GS',
  },
  {
    regNo: 1552,
    name: 'SICILIAN ICE CREAM COMPANY LIMITED',
    adba: null,
    telephone: '(905) 761-7767',
    streetAddr: '349 FOUR VALLEY DRIVE',
    city: 'Concord',
    province: 'ON',
    postalCode: 'L4K 5Z3',
  },
  {
    regNo: 1555,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(519) 537-2361',
    streetAddr: '478 INDUSTRIAL AVE.',
    city: 'WOODSTOCK',
    province: 'ON',
    postalCode: 'N4S 7L1',
  },
  {
    regNo: 1560,
    name: 'LANTIC INC.',
    adba: 'LANTIC BLENDING',
    telephone: '(416) 757-8787',
    streetAddr: '230 MIDWEST ROAD',
    city: 'SCARBOROUGH',
    province: 'ON',
    postalCode: 'M1P 3A9',
  },
  {
    regNo: 1562,
    name: 'GROBER INC.',
    adba: 'NUTRABLEND FOODS',
    telephone: '(519) 622-2500',
    streetAddr: '150 ADAMS BLVD.',
    city: 'BRANTFORD',
    province: 'ON',
    postalCode: 'N3S 7V2',
  },
  {
    regNo: 1563,
    name: 'SKJODT-BARRETT FOODS INC.',
    adba: null,
    telephone: '(905) 671-2884',
    streetAddr: '5 PRECIDIO COURT',
    city: 'BRAMPTON',
    province: 'ON',
    postalCode: 'L6S 6B7',
  },
  {
    regNo: 1565,
    name: 'WILD FLAVORS (CANADA) INC.',
    adba: null,
    telephone: '(905) 670-1108',
    streetAddr: '7315 PACIFIC CIRCLE',
    city: 'MISSISSAUGA',
    province: 'ON',
    postalCode: 'L5T 1V1',
  },
  {
    regNo: 1571,
    name: 'KERRY (CANADA) INC.',
    adba: null,
    telephone: '(519) 537-3461',
    streetAddr: '615 JACK ROSS AVE.',
    city: 'WOODSTOCK',
    province: 'ON',
    postalCode: 'N4V 1B7',
  },
  {
    regNo: 1573,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(905) 791-6100',
    streetAddr: '16 SHAFTSBURY LANE',
    city: 'BRAMPTON',
    province: 'ON',
    postalCode: 'L6T 4G7',
  },
  {
    regNo: 1575,
    name: 'CONTINENTAL INGREDIENTS CANADA INC',
    adba: null,
    telephone: '(905) 815-8158',
    streetAddr: '1170 INVICTA DRIVE',
    city: 'OAKVILLE',
    province: 'ON',
    postalCode: 'L6H 6G1',
  },
  {
    regNo: 1577,
    name: 'DURE FOODS LIMITED',
    adba: null,
    telephone: '(519) 753-5504',
    streetAddr: '120 ROY BOULEVARD',
    city: 'BRANTFORD',
    province: 'ON',
    postalCode: 'N3R 7K2',
  },
  {
    regNo: 1578,
    name: 'MODHANI INC.',
    adba: null,
    telephone: '(416) 347-3701',
    streetAddr: '21 REGAN ROAD UNIT F&G',
    city: 'BRAMPTON',
    province: 'ON',
    postalCode: 'L7A 1C5',
  },
  {
    regNo: 1579,
    name: 'METROPOLITAN ICE CREAM INC.',
    adba: null,
    telephone: '(416) 245-1335',
    streetAddr: '26 Milford Avenue',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M6M 2V8',
  },
  {
    regNo: 1581,
    name: 'TRU LABELS INC.',
    adba: 'DRY FOOD MANUFACTURER',
    telephone: '(905) 915-7555',
    streetAddr: '60 COURTLAND AVE',
    city: 'VAUGHAN',
    province: 'ON',
    postalCode: 'L4K 5B3',
  },
  {
    regNo: 1582,
    name: '1048547 ONTARIO INC',
    adba: 'SKOTIDAKIS GOAT FARM',
    telephone: '(613) 674-3183',
    streetAddr: '185 COUNTY ROAD 10',
    city: 'ST. EUGENE',
    province: 'ON',
    postalCode: 'K0B 1P0',
  },
  {
    regNo: 1585,
    name: 'REX PAK LIMITED',
    adba: null,
    telephone: '(416) 755-3324',
    streetAddr: '85 THORNMOUNT DRIVE',
    city: 'TORONTO',
    province: 'ON',
    postalCode: 'M1B 5V3',
  },
  {
    regNo: 1587,
    name: 'NEWLY WEDS FOODS CO.',
    adba: null,
    telephone: '(905) 670-7776',
    streetAddr: '450 SUPERIOR BLVD',
    city: 'MISSISSAUGA',
    province: 'ON',
    postalCode: 'L5T 2R9',
  },
  {
    regNo: 1588,
    name: 'RICH PRODUCTS OF CANADA LIMITED',
    adba: null,
    telephone: '(905) 265-4310',
    streetAddr: '149 ROWNTREE DAIRY RD.',
    city: 'WOODBRIDGE',
    province: 'ON',
    postalCode: 'L4L 6E1',
  },
  {
    regNo: 1590,
    name: 'SAPUTO DAIRY PRODUCTS CANADA INC.',
    adba: null,
    telephone: '(905) 702-7200',
    streetAddr: '279 GUELPH ST.',
    city: 'HALTON HILLS',
    province: 'ON',
    postalCode: 'L7G 4B3',
  },
  {
    regNo: 1591,
    name: 'UPPER CANADA CREAMERY INC.',
    adba: null,
    telephone: '(613) 802-8026',
    streetAddr: '11603 Waddell Rd',
    city: 'Iroquois',
    province: 'ON',
    postalCode: 'K0E 1K0',
  },
  {
    regNo: 1593,
    name: 'SAPUTO DAIRY PRODUCTS CANADA G.P.',
    adba: null,
    telephone: '(519) 941-9206',
    streetAddr: '425 RICHARDSON ROAD',
    city: 'ORANGEVILLE',
    province: 'ON',
    postalCode: 'L9W 4Z4',
  },
  {
    regNo: 1595,
    name: 'SHEPHERD GOURMET DAIRY (ONTARIO) INC.',
    adba: null,
    telephone: '(519) 349-2410',
    streetAddr: '38 ENTERPRISE DRIVE',
    city: 'ST MARYS',
    province: 'ON',
    postalCode: 'N4X 1B5',
  },
  {
    regNo: 1596,
    name: "C'ESTBON CHEESE LIMITED",
    adba: null,
    telephone: '(519) 671-5195',
    streetAddr: '4675 LINE 3, RR 3',
    city: "ST. MARY'S",
    province: 'ON',
    postalCode: 'N4X 1C6',
  },
  {
    regNo: 1598,
    name: 'SPRINGBANK CHEESE COMPANY LTD.',
    adba: null,
    telephone: '(519) 539-7411',
    streetAddr: '201 WINNETT STREET',
    city: 'WOODSTOCK',
    province: 'ON',
    postalCode: 'N4S 6A1',
  },
  {
    regNo: 1603,
    name: 'LA SUISSE NORMANDE INC.',
    adba: null,
    telephone: '(450) 588-6503',
    streetAddr: '985 RANG DE LA RIVIERE NORD  2566991 - 2567113',
    city: 'SAINT-ROCH OUEST',
    province: 'QC',
    postalCode: 'J0K 3H0',
  },
  {
    regNo: 1604,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(418) 629-3133',
    streetAddr: '466, ROUTE 132 OUEST',
    city: 'AMQUI',
    province: 'QC',
    postalCode: 'G5J 2G7',
  },
  {
    regNo: 1606,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(514) 484-8401',
    streetAddr: '7470, RUE SAINT-JACQUES OUEST',
    city: 'MONTRÉAL',
    province: 'QC',
    postalCode: 'H4B 1W4',
  },
  {
    regNo: 1611,
    name: "SOCIÉTÉ COOPÉRATIVE AGRICOLE DE L'ILE-AUX-GRUES",
    adba: 'FROMAGERIE ISLE-AUX-GRUES/LA COOP',
    telephone: '(418) 248-5842',
    streetAddr: '210 CHEMIN DU ROI',
    city: 'ISLE-AUX-GRUES',
    province: 'QC',
    postalCode: 'G0R 1P0',
  },
  {
    regNo: 1619,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(450) 773-6493',
    streetAddr: '995, RUE JOHNSON EST',
    city: 'SAINT-HYACINTHE',
    province: 'QC',
    postalCode: 'J2S 7V6',
  },
  {
    regNo: 1641,
    name: 'LAITERIE CHARLEVOIX INC.',
    adba: null,
    telephone: '(418) 435-2184',
    streetAddr: '1167 BOUL. MGR. DE LAVAL',
    city: 'BAIE-SAINT-PAUL',
    province: 'QC',
    postalCode: 'G3Z 2W7',
  },
  {
    regNo: 1644,
    name: 'SAPUTO PRODUITS LAITIERS CANADA S.E.N.C.',
    adba: null,
    telephone: '(418) 337-4287',
    streetAddr: '71 AVENUE ST-JACQUES',
    city: 'SAINT-RAYMOND',
    province: 'QC',
    postalCode: 'G3L 3X9',
  },
  {
    regNo: 1649,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(819) 336-2727',
    streetAddr: '81, RUE SAINT-FELIX',
    city: 'NOTRE-DAME-DU-BON-CONSEIL',
    province: 'QC',
    postalCode: 'J0C 1A0',
  },
  {
    regNo: 1651,
    name: 'FROMAGERIE DU CHAMP À LA MEULE INC.',
    adba: null,
    telephone: '(450) 753-9217',
    streetAddr: '3601, RUE PRINCIPALE',
    city: 'NOTRE-DAME-DE-LOURDES',
    province: 'QC',
    postalCode: 'J0K 1K0',
  },
  {
    regNo: 1666,
    name: 'SAPUTO PRODUITS LAITIERS CANADA S.E.N.C.',
    adba: null,
    telephone: '(450) 773-1004',
    streetAddr: '1195 RUE JOHNSON EST',
    city: 'SAINT-HYACINTHE',
    province: 'QC',
    postalCode: 'J2S 7Y6',
  },
  {
    regNo: 1673,
    name: 'FROMAGERIE FRITZ KAISER INC.',
    adba: null,
    telephone: '(450) 294-2207',
    streetAddr: '459 4IEME CONCESSION',
    city: 'NOYAN',
    province: 'QC',
    postalCode: 'J0J 1B0',
  },
  {
    regNo: 1680,
    name: 'SAPUTO PRODUITS LAITIERS CANADA S.E.N.C.',
    adba: null,
    telephone: '(819) 623-4350',
    streetAddr: '1485, BOUL. ALBINY PAQUETTE ',
    city: 'MONT-LAURIER',
    province: 'QC',
    postalCode: 'J9L 1M8',
  },
  {
    regNo: 1704,
    name: 'SAPUTO PRODUITS LAITIERS CANADA S.E.N.C.',
    adba: null,
    telephone: '(819) 352-2813',
    streetAddr: '1245, AVENUE FORAND',
    city: 'PLESSISVILLE',
    province: 'QC',
    postalCode: 'G6L 1X5',
  },
  {
    regNo: 1708,
    name: 'LYO-SAN INC.',
    adba: null,
    telephone: '(450) 562-8525',
    streetAddr: "500, BOUL. DE L'AEROPARC, C.P. 598",
    city: 'LACHUTE',
    province: 'QC',
    postalCode: 'J8H 3R8',
  },
  {
    regNo: 1711,
    name: 'AGROPUR COOPÉRATIVE',
    adba: 'AGROPUR - DAMAFRO',
    telephone: '(450) 797-3301',
    streetAddr: '54 RUE PRINCIPALE',
    city: 'SAINT-DAMASE',
    province: 'QC',
    postalCode: 'J0H 1J0',
  },
  {
    regNo: 1720,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(418) 641-0857',
    streetAddr: '2465, 1ERE AVENUE',
    city: 'QUÉBEC',
    province: 'QC',
    postalCode: 'G1L 3M9',
  },
  {
    regNo: 1727,
    name: 'LA FROMAGERIE DU TERROIR DE BELLECHASSE INC.',
    adba: null,
    telephone: '(418) 884-4027',
    streetAddr: '585 Boul. St-Vallier',
    city: 'SAINT-VALLIER',
    province: 'QC',
    postalCode: 'G0R 4J0',
  },
  {
    regNo: 1730,
    name: 'FROMAGERIE MIRABEL (1985) INC.',
    adba: null,
    telephone: '(613) 987-2872',
    streetAddr: '150, BOUL. LACHAPELLE',
    city: 'SAINT-JÉRÔME',
    province: 'QC',
    postalCode: 'J7Z 7L2',
  },
  {
    regNo: 1743,
    name: 'CREME GLACEE ITAL GELATI INC.',
    adba: 'ITAL GELATI',
    telephone: '(514) 322-0111',
    streetAddr: '8390, RUE LE CREUSOT',
    city: 'SAINT-LÉONARD',
    province: 'QC',
    postalCode: 'H1P 2A6',
  },
  {
    regNo: 1760,
    name: 'SAPUTO PRODUITS LAITIERS CANADA S.E.N.C.',
    adba: null,
    telephone: '(514) 328-3466',
    streetAddr: '2365, CHEMIN DE LA CÔTE DE-LIESSE',
    city: 'SAINT-LAURENT',
    province: 'QC',
    postalCode: 'H4N 2M7',
  },
  {
    regNo: 1770,
    name: 'ALBERT PERRON INC.',
    adba: 'FROMAGERIE PERRON',
    telephone: '(418) 251-3164',
    streetAddr: '156, AVENUE ALBERT PERRON',
    city: 'SAINT-PRIME',
    province: 'QC',
    postalCode: 'G8J 1L4',
  },
  {
    regNo: 1779,
    name: '6972047 CANADA INC.',
    adba: 'FERME FLORALPE',
    telephone: '(819) 427-5700',
    streetAddr: '1700, ROUTE 148',
    city: 'PAPINEAU',
    province: 'QC',
    postalCode: 'J0V 1R0',
  },
  {
    regNo: 1781,
    name: 'FROMAGERIE RANG 9 INC.',
    adba: 'ECO-DELICES INC.',
    telephone: '(819) 362-7472',
    streetAddr: '766 RANG 9 EST',
    city: 'PLESSISVILLE',
    province: 'QC',
    postalCode: 'G6L 2Y2',
  },
  {
    regNo: 1782,
    name: 'FROMAGERIE BERGERON INC.',
    adba: null,
    telephone: '(418) 886-2234',
    streetAddr: '3837, ROUTE MARIE-VICTORIN',
    city: 'SAINT-ANTOINE-DE-TILLY',
    province: 'QC',
    postalCode: 'G0S 2C0',
  },
  {
    regNo: 1784,
    name: 'LA FROMAGERIE POLYETHNIQUE INC.',
    adba: null,
    telephone: '(450) 782-2111',
    streetAddr: '235 CHEMIN ST-ROBERT',
    city: 'SAINT-ROBERT',
    province: 'QC',
    postalCode: 'JOG 1SO',
  },
  {
    regNo: 1798,
    name: "LA MAISON D'AFFINAGE MAURICE DUFOUR INC.",
    adba: null,
    telephone: '(418) 435-5692',
    streetAddr: '1339 BOUL. MGR. DE LAVAL',
    city: 'BAIE-SAINT-PAUL',
    province: 'QC',
    postalCode: 'G3Z 2X6',
  },
  {
    regNo: 1807,
    name: 'AGROPUR COOPERATIVE',
    adba: null,
    telephone: '(450) 479-6396',
    streetAddr: '1400, CHEMIN OKA',
    city: 'OKA',
    province: 'QC',
    postalCode: 'J0N 1E0',
  },
  {
    regNo: 1808,
    name: 'FROMAGERIE DU DOMAINE FÉODAL INC.',
    adba: null,
    telephone: '(450) 836-7979',
    streetAddr: '1303 RIVIERE BAYONNE SUD',
    city: 'BERTHIERVILLE',
    province: 'QC',
    postalCode: 'J0K 1A0',
  },
  {
    regNo: 1821,
    name: "FROMAGERIE L'ANCÊTRE INC.",
    adba: null,
    telephone: '(819) 233-9157',
    streetAddr: '1615 BOUL PORT-ROYAL',
    city: 'BÉCANCOUR',
    province: 'QC',
    postalCode: 'G9H 1X7',
  },
  {
    regNo: 1828,
    name: 'LE FROMAGE AU VILLAGE INC.',
    adba: null,
    telephone: '(819) 625-2255',
    streetAddr: '45 NOTRE-DAME OUEST C.P. 309',
    city: 'LORRAINVILLE',
    province: 'QC',
    postalCode: 'J0Z 2R0',
  },
  {
    regNo: 1846,
    name: 'LES ALIMENTS KARNIE INC.',
    adba: null,
    telephone: '(450) 384-9633',
    streetAddr: '9450 RUE CHARLES DE LA TOUR',
    city: 'MONTRÉAL',
    province: 'QC',
    postalCode: 'H4N 1M2',
  },
  {
    regNo: 1848,
    name: 'FROMAGERIE DU PIED-DE-VENT INC.',
    adba: null,
    telephone: '(418) 969-9292',
    streetAddr: '149 CHEMIN DE LA POINTE-BASSE',
    city: 'HAVRE-AUX-MAISONS',
    province: 'QC',
    postalCode: 'G4T 5H7',
  },
  {
    regNo: 1850,
    name: '7608187 CANADA INC',
    adba: "LA TRAPPE À FROMAGE DE L'OUTAOUAIS",
    telephone: '(819) 243-6411',
    streetAddr: '200 RUE BELLEHUMEUR',
    city: 'GATINEAU',
    province: 'QC',
    postalCode: 'J8T 8N6',
  },
  {
    regNo: 1852,
    name: 'AGROPUR COOPERATIVE',
    adba: 'LES CRÈMES GLACÉES LEBEL INC.',
    telephone: '(514) 703-6788',
    streetAddr: '724 RUE PRINCIPALE',
    city: 'LA CHUTE',
    province: 'QC',
    postalCode: 'J8H 1Z4',
  },
  {
    regNo: 1857,
    name: 'FROMAGERIE LE DÉTOUR (2003) INC.',
    adba: 'FROMAGERIE LE DÉTOUR',
    telephone: '(418) 899-7000',
    streetAddr: '120, COMMERCIALE NORD',
    city: 'TÉMISCOUATA-SUR-LE-LAC',
    province: 'QC',
    postalCode: 'G0L 1X0',
  },
  {
    regNo: 1863,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(819) 765-3411',
    streetAddr: '9, RUE LAFRENIERE',
    city: 'LAVERLOCHÈRE',
    province: 'QC',
    postalCode: 'J0Z 2P0',
  },
  {
    regNo: 1865,
    name: '9015-4931 QUÉBEC INC.',
    adba: null,
    telephone: '(819) 333-1121',
    streetAddr: '604,2E RUE EST',
    city: 'LASARRE',
    province: 'QC',
    postalCode: 'J9Z 2S5',
  },
  {
    regNo: 1874,
    name: '9329-8800 QUÉBEC INC.',
    adba: 'FROMAGERIE MARIE KADÉ',
    telephone: '(450) 419-4477',
    streetAddr: '1921 BOUL LIONEL BERTRAND',
    city: 'BOISBRIAND',
    province: 'QC',
    postalCode: 'J7H 1N8',
  },
  {
    regNo: 1900,
    name: 'SAPUTO PRODUITS LAITIERS CANADA S.E.N.C.',
    adba: null,
    telephone: '(514) 328-3317',
    streetAddr: '6869 BOUL. METROPOLITAIN EST',
    city: 'SAINT-LÉONARD',
    province: 'QC',
    postalCode: 'H1P 1X8',
  },
  {
    regNo: 1908,
    name: 'FERME RAYMOND ALARY & FILS (1981) INC.',
    adba: 'LES FROMAGIERS DE LA TABLE RONDE',
    telephone: '(450) 530-2436',
    streetAddr: '317, BOUL STE-SOPHIE',
    city: 'SAINTE-SOPHIE',
    province: 'QC',
    postalCode: 'J5J 2V1',
  },
  {
    regNo: 1916,
    name: 'FROMAGERIE LA STATION INC.',
    adba: null,
    telephone: '(819) 835-5301',
    streetAddr: '440 CHEMIN HATLEY',
    city: 'COMPTON',
    province: 'QC',
    postalCode: 'J0B 1L0',
  },
  {
    regNo: 1923,
    name: "FROMAGERIE L'ANCÊTRE INC.",
    adba: null,
    telephone: '(819) 233-9157',
    streetAddr: '3645 BOUL. PORT-ROYAL, LOCAL #1',
    city: 'BÉCANCOUR',
    province: 'QC',
    postalCode: 'G9H 1Y7',
  },
  {
    regNo: 1935,
    name: 'FERME DOMAINE DE LA RIVIÈRE INC',
    adba: 'FROMAGERIE MÉDARD',
    telephone: '(418) 345-2407',
    streetAddr: '10 CHEMIN DE QUEN',
    city: 'SAINT-GÉDÉON',
    province: 'QC',
    postalCode: 'G0W 2P0',
  },
  {
    regNo: 1936,
    name: "LA MAISON D'AFFINAGE BERGERON INC.",
    adba: null,
    telephone: '(418) 831-1193',
    streetAddr: '865 ROUTE DES RIVIÈRES',
    city: 'LÈVIS',
    province: 'QC',
    postalCode: 'G7A 2V2',
  },
  {
    regNo: 1947,
    name: '9140-5621 QUÉBEC INC.',
    adba: 'FROMAGERIE DU PRESBYTÈRE',
    telephone: '(819) 358-6555',
    streetAddr: '222, RUE PRINCIPALE',
    city: 'STE-ÉLIZABETH',
    province: 'QC',
    postalCode: 'J0A 1M0',
  },
  {
    regNo: 1949,
    name: 'YOPLAIT LIBERTÉ CANADA CO.',
    adba: null,
    telephone: '(450) 252-1949',
    streetAddr: '6285, AVENUE CHOQUETTE',
    city: 'ST-HYACINTHE',
    province: 'QC',
    postalCode: 'J2S 8L2',
  },
  {
    regNo: 1953,
    name: 'LA FERME A.B.ET G. BLACKBURN INC.',
    adba: 'FROMAGERIE BLACKBURN',
    telephone: '(418) 547-4153',
    streetAddr: '4353, Chemin Saint-Benoît',
    city: 'Jonquière Saguenay',
    province: 'QC',
    postalCode: 'G7X 7V5',
  },
  {
    regNo: 1978,
    name: 'LA MOUTONNIÈRE INC.',
    adba: null,
    telephone: '(819) 382-2300',
    streetAddr: '3456 PRINCIPALE',
    city: 'STE-HÉLÈNE-DE-CHESTER',
    province: 'QC',
    postalCode: 'G0P 1H0',
  },
  {
    regNo: 1980,
    name: 'FROMAGERIE LEMAIRE LTEE',
    adba: null,
    telephone: '(819) 478-0601',
    streetAddr: '2095 ROUTE 122',
    city: 'SAINT-CYRILLE DE WENDOVER',
    province: 'QC',
    postalCode: 'J1Z 1B9',
  },
  {
    regNo: 1984,
    name: '9206-1431 QUÉBEC INC.',
    adba: 'La fromagerie les folies bergères',
    telephone: '(819) 983-4010',
    streetAddr: '955, ROUTE 317',
    city: 'ST-SIXTE',
    province: 'QC',
    postalCode: 'J0X 3B0',
  },
  {
    regNo: 1996,
    name: 'LA FROMAGERIE CHAMPÊTRE INC.',
    adba: null,
    telephone: '(450) 654-1308',
    streetAddr: '415 RUE DES INDUSTRIES',
    city: 'Repentigny',
    province: 'QC',
    postalCode: 'J5Z 4Y8',
  },
  {
    regNo: 1997,
    name: 'KRINOS FOODS CANADA LTD.',
    adba: 'LES ALIMENTS KRINOS FOODS',
    telephone: '(514) 273-8529',
    streetAddr: '5555 BOUL THIMENS',
    city: 'MONTRÉAL',
    province: 'QC',
    postalCode: 'H4R 2H4',
  },
  {
    regNo: 2000,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(450) 777-5309',
    streetAddr: '1100, OMER DESLAURIERS',
    city: 'GRANBY',
    province: 'QC',
    postalCode: 'J2J 0S7',
  },
  {
    regNo: 2002,
    name: "LAITERIE DE L'OUTAOUAIS INC.",
    adba: null,
    telephone: '(819) 663-7665',
    streetAddr: '275, CHEMIN INDUSTRIEL',
    city: 'GATINEAU',
    province: 'QC',
    postalCode: 'J8R 3V8',
  },
  {
    regNo: 2005,
    name: 'LES FROMAGES LATINO INC.',
    adba: 'FROMAGERIE DE LA FERME',
    telephone: '(450) 788-2409',
    streetAddr: "509, RANG DU BORD-DE- L'EAU",
    city: 'SAINT-AIMÉ',
    province: 'QC',
    postalCode: 'J0G 1K0',
  },
  {
    regNo: 2014,
    name: 'FROMAGERIE ROY INC.',
    adba: null,
    telephone: '(450) 271-7203',
    streetAddr: '3585 RUE QUEEN',
    city: 'RAWDON',
    province: 'QC',
    postalCode: 'J0K 1S0',
  },
  {
    regNo: 2047,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(418) 774-9848',
    streetAddr: '75 AVENUE LAMBERT',
    city: 'BEAUCEVILLE',
    province: 'QC',
    postalCode: 'G5X 3N5',
  },
  {
    regNo: 2051,
    name: '7717652 CANADA INC.',
    adba: 'FROMAGERIE MONTEBELLO INC. ',
    telephone: '(819) 309-0541',
    streetAddr: '687A, RUE NOTRE-DAME',
    city: 'MONTEBELLO',
    province: 'QC',
    postalCode: 'J0V 1L0',
  },
  {
    regNo: 2194,
    name: 'LAITERIE CHALIFOUX INC.',
    adba: null,
    telephone: '(450) 743-4439',
    streetAddr: '1049 BOULEVARD FISET',
    city: 'SOREL-TRACY',
    province: 'QC',
    postalCode: 'J3P 7R2',
  },
  {
    regNo: 2201,
    name: 'SOYLUTIONS INC.',
    adba: null,
    telephone: '(418) 845-9888',
    streetAddr: '1629, AVENUE DES AFFAIRES',
    city: 'Québec',
    province: 'QC',
    postalCode: 'G3J 1Y7',
  },
  {
    regNo: 2250,
    name: 'KERRY (CANADA) INC',
    adba: null,
    telephone: '(418) 833-3301',
    streetAddr: '187 BOUL. BEGIN',
    city: 'SAINTE-CLAIRE',
    province: 'QC',
    postalCode: 'G0R 2V0',
  },
  {
    regNo: 2286,
    name: 'FROMAGERIE ST-FIDÈLE INC.',
    adba: null,
    telephone: '(418) 434-2220',
    streetAddr: '2815 BOUL. MALCOM- FRASER',
    city: 'LA MALBAIE',
    province: 'QC',
    postalCode: 'G5A 2J2',
  },
  {
    regNo: 2295,
    name: 'FROMAGES LA CHAUDIERE INC.',
    adba: null,
    telephone: '(819) 583-4664',
    streetAddr: '3226, RUE LAVAL NORD',
    city: 'LAC-MÉGANTIC',
    province: 'QC',
    postalCode: 'G6B 1A4',
  },
  {
    regNo: 2369,
    name: 'GREEK MOUNTAIN CHEESE LTD',
    adba: null,
    telephone: '(450) 839-2729',
    streetAddr: '220 RUE ST-JACQUES',
    city: 'SAINT-JACQUES',
    province: 'QC',
    postalCode: 'J0K 2R0',
  },
  {
    regNo: 2413,
    name: 'ALIMENTS ULTIMA INC./ULTIMA FOODS INC.',
    adba: null,
    telephone: '(450) 375-1993',
    streetAddr: '500, RUE PRINCIPALE',
    city: 'GRANBY',
    province: 'QC',
    postalCode: 'J2G 2X2',
  },
  {
    regNo: 2538,
    name: 'LES FROMAGES LATINO INC.',
    adba: "FROMAGERIE L'OISEAU BLEU",
    telephone: '(450) 788-2409',
    streetAddr: '525, BOUL. INDUSTRIEL',
    city: 'ASBESTOS',
    province: 'QC',
    postalCode: 'J1T 0A4',
  },
  {
    regNo: 2702,
    name: '9113-0476 QUÉBEC INC',
    adba: 'FROMAGERIE BOIVIN',
    telephone: '(418) 544-2622',
    streetAddr: '2152 CHEMIN SAINT- JOSEPH',
    city: 'LA BAIE',
    province: 'QC',
    postalCode: 'G7B 3N9',
  },
  {
    regNo: 2751,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(819) 758-6240',
    streetAddr: '75, BOUL. PIERRE-ROUX EST',
    city: 'VICTORIAVILLE',
    province: 'QC',
    postalCode: 'G6T 1S8',
  },
  {
    regNo: 2849,
    name: 'LAITERIE DE LA BAIE LTÉE',
    adba: null,
    telephone: '(418) 544-0954',
    streetAddr: '1093, RUE AIME-GRAVEL',
    city: 'LA BAIE',
    province: 'QC',
    postalCode: 'G7B 2M6',
  },
  {
    regNo: 2889,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(514) 332-2220',
    streetAddr: '333 BOUL. LEBEAU',
    city: 'VILLE-SAINT-LAURENT',
    province: 'QC',
    postalCode: 'H4N 1S3',
  },
  {
    regNo: 2982,
    name: 'MAURICE ST-LAURENT LTEE',
    adba: null,
    telephone: '(418) 343-3655',
    streetAddr: '735 RANG 6 NORD',
    city: 'SAINT-BRUNO',
    province: 'QC',
    postalCode: 'G0W 2L0',
  },
  {
    regNo: 3000,
    name: 'LAITERIE DE COATICOOK, LIMITÉE',
    adba: null,
    telephone: '(819) 849-2272',
    streetAddr: '1000 RUE CHILD',
    city: 'COATICOOK',
    province: 'QC',
    postalCode: 'J1A 2S5',
  },
  {
    regNo: 3015,
    name: 'LACTALIS CANADA INC.',
    adba: 'WINCHESTER CHEESE COLD STORAGE',
    telephone: '(613) 774-2297',
    streetAddr: '694 St. Lawrence St. S',
    city: 'Winchester',
    province: 'ON',
    postalCode: 'K0C 2K0',
  },
  {
    regNo: 3025,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(819) 362-7338',
    streetAddr: '2400, RUE DE LA COOPÉRATIVE.',
    city: 'PLESSISVILLE',
    province: 'QC',
    postalCode: 'G6L 3G8',
  },
  {
    regNo: 3140,
    name: 'AGRILAIT, COOPÉRATIVE AGRICOLE',
    adba: null,
    telephone: '(819) 396-2022',
    streetAddr: "83, ROUTE DE L'EGLISE",
    city: 'SAINT-GUILLAUME',
    province: 'QC',
    postalCode: 'J0C 1L0',
  },
  {
    regNo: 3301,
    name: 'PRO-AMINO INTERNATIONAL INC.',
    adba: null,
    telephone: '(450) 491-7106',
    streetAddr: '500 RUE GUINDON, SUITE 111',
    city: 'SAINT-EUSTACHE',
    province: 'QC',
    postalCode: 'J7R 5B4',
  },
  {
    regNo: 3303,
    name: 'PHARMALAB INC.',
    adba: null,
    telephone: '(418) 833-7603',
    streetAddr: '8750 BOULEVARD GUILLAUME-COUTURE',
    city: 'LÉVIS',
    province: 'QC',
    postalCode: 'G6V 9G9',
  },
  {
    regNo: 3305,
    name: 'BARIATRIX NUTRITION INC.',
    adba: null,
    telephone: '(514) 633-7455',
    streetAddr: '4905 RUE FAIRWAY',
    city: 'LACHINE',
    province: 'QC',
    postalCode: 'H8T 1B7',
  },
  {
    regNo: 3330,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(450) 443-1220',
    streetAddr: '4800 ARMAND-FRAPPIER',
    city: 'ST-HUBERT',
    province: 'QC',
    postalCode: 'J3Z 1G5',
  },
  {
    regNo: 3451,
    name: 'SMUCKER  FOODS OF CANADA CORP.',
    adba: null,
    telephone: '(819) 569-3614',
    streetAddr: '1212, RUE WELLINGTON SUD',
    city: 'SHERBROOKE',
    province: 'QC',
    postalCode: 'J1H 5E7',
  },
  {
    regNo: 3460,
    name: 'CORPORATION DES MOINES BÉNÉDICTINS',
    adba: null,
    telephone: '(877) 343-4336',
    streetAddr: '1 RUE PRINCIPALE',
    city: 'SAINT-BENOÎT-DU-LAC',
    province: 'QC',
    postalCode: 'J0B 2M0',
  },
  {
    regNo: 3488,
    name: 'LAITERIE CHAGNON LTÉE',
    adba: null,
    telephone: '(450) 539-3535',
    streetAddr: '550 RUE LEWIS OUEST',
    city: 'WATERLOO',
    province: 'QC',
    postalCode: 'J0E 2N0',
  },
  {
    regNo: 3506,
    name: 'KRAFT HEINZ CANADA ULC',
    adba: null,
    telephone: '(514) 340-2699',
    streetAddr: '8600, CHEMIN DEVONSHIRE',
    city: 'VILLE MONT-ROYAL',
    province: 'QC',
    postalCode: 'J0L 2K0',
  },
  {
    regNo: 3514,
    name: 'DANONE INC.',
    adba: null,
    telephone: '(450) 655-7331',
    streetAddr: '100, RUE DE LAUZON',
    city: 'BOUCHERVILLE',
    province: 'QC',
    postalCode: 'J4B 1E6',
  },
  {
    regNo: 3530,
    name: 'NUTRINOR COOPÉRATIVE',
    adba: null,
    telephone: '(418) 668-9285',
    streetAddr: '1545, BOUL. ST-JUDE',
    city: 'ALMA',
    province: 'QC',
    postalCode: 'G8B 3L3',
  },
  {
    regNo: 3531,
    name: 'LA PINTE INC.',
    adba: null,
    telephone: '(819) 867-0131',
    streetAddr: '1060 RUE WESTMOUNT',
    city: "AYER'S CLIFF",
    province: 'QC',
    postalCode: 'J0B 1C0',
  },
  {
    regNo: 3610,
    name: 'AMALGAMATED DAIRIES LIMITED',
    adba: null,
    telephone: '(902) 888-5088',
    streetAddr: '79 WATER ST',
    city: 'SUMMERSIDE',
    province: 'PEI',
    postalCode: 'C1N 1A6',
  },
  {
    regNo: 3612,
    name: 'AMALGAMATED DAIRIES LIMITED',
    adba: 'PERFECTION FOODS (1991) LTD.',
    telephone: '(902) 566-5515',
    streetAddr: '215 FITZROY STREET',
    city: 'CHARLOTTETOWN',
    province: 'PEI',
    postalCode: 'C1A 1S6',
  },
  {
    regNo: 3616,
    name: "COW'S INC.",
    adba: null,
    telephone: '(902) 393-8308',
    streetAddr: '12 MILKY WAY',
    city: 'CHARLOTTETOWN',
    province: 'PEI',
    postalCode: 'C1E 2E2',
  },
  {
    regNo: 3628,
    name: 'AMALGAMATED DAIRIES LIMITED',
    adba: null,
    telephone: '(902) 859-2323',
    streetAddr: 'GASPE ROAD',
    city: "O'LEARY",
    province: 'PEI',
    postalCode: 'COB 1VO',
  },
  {
    regNo: 3637,
    name: 'AMALGAMATED DAIRIES LIMITED',
    adba: null,
    telephone: '(902) 566-5411',
    streetAddr: '50 FOURTH STREET',
    city: 'CHARLOTTETOWN',
    province: 'PEI',
    postalCode: 'C1E 2B5',
  },
  {
    regNo: 3642,
    name: 'AMALGAMATED DAIRIES LIMITED',
    adba: null,
    telephone: '(902) 888-5055',
    streetAddr: '36 GREENWOOD DR.',
    city: 'SUMMERSIDE',
    province: 'PEI',
    postalCode: 'C1N 4S6',
  },
  {
    regNo: 3702,
    name: 'AGROPUR COOPERATIVE',
    adba: null,
    telephone: '(902) 835-3373',
    streetAddr: '745 HAMMONDS PLAINS RD',
    city: 'BEDFORD',
    province: 'NS',
    postalCode: 'B4B 1A8',
  },
  {
    regNo: 3703,
    name: 'AGROPUR COOPERATIVE',
    adba: 'SCOTSBURN CO-OPERATIVE',
    telephone: '(514) 703-6788',
    streetAddr: '85 BLAKENEY AVE',
    city: 'TRURO',
    province: 'NS',
    postalCode: 'B2N 6W9',
  },
  {
    regNo: 3704,
    name: 'FOX HILL CHEESE HOUSE',
    adba: null,
    telephone: '(902) 542-3599',
    streetAddr: '1678 CHURCH STREET',
    city: 'PORT WILLIAMS',
    province: 'NS',
    postalCode: 'B0P 1T0',
  },
  {
    regNo: 3705,
    name: 'HOLMESTEAD CHEESE SALES INC.',
    adba: null,
    telephone: '(902) 847-9034',
    streetAddr: '2439 HARMONY ROAD',
    city: 'AYELSFORD',
    province: 'NS',
    postalCode: 'B0P 1C0',
  },
  {
    regNo: 3712,
    name: 'Knoydart Farm Limited',
    adba: null,
    telephone: '(902) 867-1305',
    streetAddr: '7037 Route 245, Knoydart',
    city: 'MERIGOMISH',
    province: 'NS',
    postalCode: 'B0K 1G0',
  },
  {
    regNo: 3715,
    name: 'AGROPUR COOPÉRATIVE',
    adba: null,
    telephone: '(902) 895-7906',
    streetAddr: '1024 Salmon River Road',
    city: 'TRURO',
    province: 'NS',
    postalCode: 'B2N 5C1',
  },
  {
    regNo: 3747,
    name: 'SAPUTO DAIRY PRODUCTS CANADA G.P.',
    adba: null,
    telephone: '(902) 468-6455',
    streetAddr: '180 JOSEPH ZATZMAN DR., BURNSIDE',
    city: 'DARTMOUTH',
    province: 'NS',
    postalCode: 'B3B 1L9',
  },
  {
    regNo: 3801,
    name: 'SAPUTO DAIRY PRODUCTS CANADA G. P.',
    adba: null,
    telephone: '(506) 632-6600',
    streetAddr: '91 MILLIDGE AVENUE',
    city: 'SAINT JOHN',
    province: 'NB',
    postalCode: 'E2K 2M3',
  },
  {
    regNo: 3808,
    name: 'AGROPUR COOPERATIVE',
    adba: null,
    telephone: '(506) 432-1950',
    streetAddr: '49 Milk Board Road',
    city: 'SUSSEX',
    province: 'NB',
    postalCode: 'E4E 5L2',
  },
  {
    regNo: 3810,
    name: 'LA BERGERIE AUX 4 VENTS LTEE',
    adba: null,
    telephone: '(506) 525-9633',
    streetAddr: '100 CH ALBAN LEGER',
    city: 'SAINTE-MARIE-DE-KENT',
    province: 'NB',
    postalCode: 'E4S 1N3',
  },
  {
    regNo: 3847,
    name: 'AGROPUR COOPERATIVE',
    adba: null,
    telephone: '(506) 627-7720',
    streetAddr: '255 LAWLOR LANE',
    city: 'MIRAMICHI',
    province: 'NB',
    postalCode: 'E1V 2C9',
  },
  {
    regNo: 3904,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(204) 725-8633',
    streetAddr: '365 PARK AVENUE EAST',
    city: 'BRANDON',
    province: 'MB',
    postalCode: 'R7A 7A5',
  },
  {
    regNo: 3907,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(204) 233-1441',
    streetAddr: '738 ST. JOSEPH STREET',
    city: 'WINNIPEG',
    province: 'MB',
    postalCode: 'R2H 3A3',
  },
  {
    regNo: 3925,
    name: 'PRAIRIE WEST ICE CREAM INC.',
    adba: null,
    telephone: '(204) 663-7031',
    streetAddr: '7 - 130 OMANDS CREEK BLVD.',
    city: 'WINNIPEG',
    province: 'MB',
    postalCode: 'R2R 1V7',
  },
  {
    regNo: 3929,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(204) 379-2571',
    streetAddr: '9 PROVINCIAL ROAD 240 SOUTH',
    city: 'ST. CLAUDE',
    province: 'MB',
    postalCode: 'R0G 1Z0',
  },
  {
    regNo: 3930,
    name: 'CREMERIE NOTRE-DAME CREAMERY LTD.',
    adba: null,
    telephone: '(204) 248-2212',
    streetAddr: '35 PROVENCHER ST.',
    city: 'NOTRE DAME DE LOURDES',
    province: 'MB',
    postalCode: 'R0G 1M0',
  },
  {
    regNo: 3941,
    name: 'SANTORINI DAIRIES INC.',
    adba: null,
    telephone: '(204) 290-5571',
    streetAddr: '610 DUFFERIN AVENUE',
    city: 'WINNIPEG',
    province: 'MB',
    postalCode: 'R2W 2Z2',
  },
  {
    regNo: 3949,
    name: 'Agropur Coopérative',
    adba: null,
    telephone: '(204) 697-2155',
    streetAddr: '940 CENTURY STREET',
    city: 'WINNIPEG',
    province: 'MB',
    postalCode: 'R3H 0V7',
  },
  {
    regNo: 3955,
    name: 'UNIVERSITY OF MANITOBA',
    adba: null,
    telephone: '(204) 474-8180',
    streetAddr: '112 DAFOE ROAD',
    city: 'WINNIPEG',
    province: 'MB',
    postalCode: 'R3T 2N2',
  },
  {
    regNo: 3976,
    name: 'BOTHWELL CHEESE INC.',
    adba: null,
    telephone: '(204) 391-0979',
    streetAddr: '61 MAIN STREET N.',
    city: 'NEW BOTHWELL',
    province: 'MB',
    postalCode: 'R0A 1C0',
  },
  {
    regNo: 3977,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(204) 434-6408',
    streetAddr: '26 ELM AVENUE NORTH LOT DES 17/19',
    city: 'GRUNTHAL',
    province: 'MB',
    postalCode: 'R0A 0R0',
  },
  {
    regNo: 3999,
    name: 'PREMIER PACKAGING SERVICES INC.',
    adba: 'MEDALLION MILK CO.',
    telephone: '(204) 233-7220',
    streetAddr: '221  Sheppard St',
    city: 'WINNIPEG',
    province: 'MB',
    postalCode: 'R2X 2X1',
  },
  {
    regNo: 4000,
    name: 'THE SASKATOON COLOSTRUM COMPANY LTD.',
    adba: null,
    telephone: '(306) 221-4132',
    streetAddr: '30 MOLARO PLACE',
    city: 'SASKATOON',
    province: 'SK',
    postalCode: 'S7K 6A2',
  },
  {
    regNo: 4015,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(306) 668-6833',
    streetAddr: '122 WAKOOMA STREET',
    city: 'SASKATOON',
    province: 'SK',
    postalCode: 'S7K 3P1',
  },
  {
    regNo: 4066,
    name: 'The Saskatchewan Food Industry Development Centre Inc.',
    adba: 'The Food Centre',
    telephone: '(306) 933-7555',
    streetAddr: '52 Innovation Boulevard',
    city: 'SASKATOON',
    province: 'SK',
    postalCode: 'S7N 2V3',
  },
  {
    regNo: 4202,
    name: "ALBERTA CHEESE COMPANY (FRANCO'S BRAND) LTD.",
    adba: null,
    telephone: '(403) 279-4353',
    streetAddr: '2730-84 Avenue SE',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T2C 1C7',
  },
  {
    regNo: 4203,
    name: 'AGROPUR COOPERATIVE',
    adba: null,
    telephone: '(780) 488-2214',
    streetAddr: '13944 YELLOWHEAD TRAIL',
    city: 'EDMONTON',
    province: 'AB',
    postalCode: 'T5L 3C2',
  },
  {
    regNo: 4206,
    name: '1163458 ALBERTA LTD.',
    adba: 'CRYSTAL SPRINGS CHEESE',
    telephone: '(403) 381-8488',
    streetAddr: 'SE-15-10-22-W4',
    city: 'COALHURST',
    province: 'AB',
    postalCode: 'T0L 0V0',
  },
  {
    regNo: 4208,
    name: 'AGROPUR COOPERATIVE',
    adba: 'Agropur, Lethbridge',
    telephone: '(403) 381-4024',
    streetAddr:
      'BLOCK 1 PLAN 901, 1046, SE 7-10-21-W4 COUNTY OF LETHBRIDGE NO. 26',
    city: 'DIAMOND CITY',
    province: 'AB',
    postalCode: 'T0K 0T0',
  },
  {
    regNo: 4210,
    name: 'ROCK RIDGE DAIRY LTD.',
    adba: null,
    telephone: '(403) 783-4312',
    streetAddr: '422046 RR 271 NE 14-42 -27-W4',
    city: 'PONOKA',
    province: 'AB',
    postalCode: 'T4J 1R3',
  },
  {
    regNo: 4214,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(403) 568-3812',
    streetAddr: '5434 44th STREET NORTH EAST',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T3J 3K7',
  },
  {
    regNo: 4231,
    name: '1228300 ALBERTA LTD.',
    adba: 'MOTHER DAIRY',
    telephone: '(587) 352-9263',
    streetAddr: '1117 - 5150, 47 STREET  N. E.',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T3J 4N4',
  },
  {
    regNo: 4268,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(403) 357-3855',
    streetAddr: '5410 GAETZ AVENUE',
    city: 'RED DEER',
    province: 'AB',
    postalCode: 'T4N 4B5',
  },
  {
    regNo: 4285,
    name: 'FOOTHILLS CREAMERY LTD.',
    adba: null,
    telephone: '(403) 263-7725',
    streetAddr: '2825 BONNYBROOK SE',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T2G 4N1',
  },
  {
    regNo: 4289,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(780) 447-8346',
    streetAddr: '16110 - 116 AVE.',
    city: 'EDMONTON',
    province: 'AB',
    postalCode: 'T5M 3V4',
  },
  {
    regNo: 4332,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(403) 380-5209',
    streetAddr: '3410 24 AVENUE NORTH',
    city: 'LETHBRIDGE',
    province: 'AB',
    postalCode: 'T1H 5K3',
  },
  {
    regNo: 4337,
    name: 'LACTALIS CANADA INC.',
    adba: null,
    telephone: '(403) 221-9500',
    streetAddr: '1939 CENTRE AVENUE SOUTH EAST',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T2E 0A8',
  },
  {
    regNo: 4352,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(403) 626-3691',
    streetAddr: '82 MAIN AVENUE SOUTH WEST',
    city: 'GLENWOOD',
    province: 'AB',
    postalCode: 'T0K 2R0',
  },
  {
    regNo: 4358,
    name: 'CLOVER LEAF CHEESE LTD.',
    adba: null,
    telephone: '(403) 250-3780',
    streetAddr: '1201  45 AVENUE N.E.',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T2E 2P2',
  },
  {
    regNo: 4360,
    name: 'AGROPUR COOPÉRATIVE',
    adba: 'AGROPUR CANADA',
    telephone: '(780) 451-0817',
    streetAddr: '11135  151 STREET',
    city: 'EDMONTON',
    province: 'AB',
    postalCode: 'T5M 1X3',
  },
  {
    regNo: 4365,
    name: "MACKAY'S COCHRANE ICE CREAM (2011) LTD.",
    adba: null,
    telephone: '(403) 932-2776',
    streetAddr: '121 RIVER AVENUE',
    city: 'COCHRANE',
    province: 'AB',
    postalCode: 'T4C 2C2',
  },
  {
    regNo: 4380,
    name: 'PARMX CHEESE CO LTD',
    adba: 'PARMX CHEESE COMPANY',
    telephone: '(403) 237-0707',
    streetAddr: '4117 16A STREET SOUTH EAST',
    city: 'CALGARY',
    province: 'AB',
    postalCode: 'T2G 3T7',
  },
  {
    regNo: 4381,
    name: 'BLES-WOLD YOGURT INC.',
    adba: null,
    telephone: '(403) 782-3322',
    streetAddr: 'RR 5',
    city: 'LACOMBE',
    province: 'AB',
    postalCode: 'T4L 2N5',
  },
  {
    regNo: 4389,
    name: "FIASCO GELATO CAFÉ'S LTD.",
    adba: null,
    telephone: '(403) 452-3150',
    streetAddr: '110-221 19 STREET SE',
    city: 'Calgary',
    province: 'AB',
    postalCode: 'T2E 7M2',
  },
  {
    regNo: 4390,
    name: 'NEWLY WEDS FOODS CO.',
    adba: null,
    telephone: '(780) 414-9500',
    streetAddr: '9110   23 AVENUE',
    city: 'EDMONTON',
    province: 'AB',
    postalCode: 'T6N 1H9',
  },
  {
    regNo: 4391,
    name: 'ALBERTA AGRICULTURE AND FORESTRY',
    adba: 'FOOD PROCESSING DEVELOPMENT CENTRE',
    telephone: '(780) 980-4872',
    streetAddr: '6309  45 STREET',
    city: 'LEDUC',
    province: 'AB',
    postalCode: 'T9E 7C5',
  },
  {
    regNo: 4393,
    name: 'TIRAS DAIRIES INC.',
    adba: null,
    telephone: '(780) 608-2487',
    streetAddr: '3712 42 AVENUE',
    city: 'CAMROSE',
    province: 'AB',
    postalCode: 'T4V 4W3',
  },
  {
    regNo: 4398,
    name: 'THE CHEESE FACTORY INC',
    adba: null,
    telephone: '(780) 450-2143',
    streetAddr: '8943 82 AVENUE NW',
    city: 'EDMONTON',
    province: 'AB',
    postalCode: 'T6C 0Z2',
  },
  {
    regNo: 4413,
    name: '0540790 B.C. LTD.',
    adba: 'BENDICK ICE CREAM FACTORY LTD.',
    telephone: '(604) 482-3188',
    streetAddr: '8262 MANITOBA STREET',
    city: 'VANCOUVER',
    province: 'BC',
    postalCode: 'V5X 3A2',
  },
  {
    regNo: 4415,
    name: 'AGROPUR COOPÉRATIVE',
    adba: 'ISLAND FARMS',
    telephone: '(250) 360-5260',
    streetAddr: '2220 DOWLER PLACE',
    city: 'VICTORIA',
    province: 'BC',
    postalCode: 'V8W 2M1',
  },
  {
    regNo: 4419,
    name: '"D" DUTCHMEN DAIRY LTD.',
    adba: null,
    telephone: '(250) 836-4304',
    streetAddr: '1321 MAIER ROAD',
    city: 'SICAMOUS',
    province: 'BC',
    postalCode: 'V0E 2V1',
  },
  {
    regNo: 4420,
    name: 'FIT FOODS LTD.',
    adba: null,
    telephone: '(604) 472-2054',
    streetAddr: '1589 Kebet Way',
    city: 'PORT COQUITLAM',
    province: 'BC',
    postalCode: 'V3C 6L5',
  },
  {
    regNo: 4426,
    name: 'NATURAL PASTURES CHEESE COMPANY LTD',
    adba: 'NATURAL FARMS LTD.',
    telephone: '(250) 334-4422',
    streetAddr: '635 MCPHEE AVENUE',
    city: 'COURTENAY',
    province: 'BC',
    postalCode: 'V9N 2Z7',
  },
  {
    regNo: 4429,
    name: 'VITALUS NUTRITION INC.',
    adba: null,
    telephone: '(604) 807-4840',
    streetAddr: '3911 MT LEHMAN ROAD',
    city: 'ABBOTSFORD',
    province: 'BC',
    postalCode: 'V2T 5W5',
  },
  {
    regNo: 4431,
    name: 'JERSEYLAND ORGANICS LTD.',
    adba: null,
    telephone: '(250) 442-8112',
    streetAddr: '2690 ALMOND GARDENS ROAD EAST',
    city: 'GRAND FORKS',
    province: 'BC',
    postalCode: 'V0H 1H4',
  },
  {
    regNo: 4432,
    name: 'CASTLE CHEESE (WEST) INC.',
    adba: null,
    telephone: '(250) 547-2100',
    streetAddr: '1834 SHUSWAP AVENUE',
    city: 'LUMBY',
    province: 'BC',
    postalCode: 'V0E 2G0',
  },
  {
    regNo: 4433,
    name: 'ULTIMA FOODS INC.',
    adba: 'OLYMPIC, DIVISION OF ULTIMA FOODS INC.',
    telephone: '(604) 952-7078',
    streetAddr: '7178 VANTAGE WAY',
    city: 'DELTA',
    province: 'BC',
    postalCode: 'V4G 1K7',
  },
  {
    regNo: 4434,
    name: 'VERKA FOOD PRODUCTS LTD.',
    adba: null,
    telephone: '(604) 214-0005',
    streetAddr: '2340 VAUXHALL PLACE',
    city: 'RICHMOND',
    province: 'BC',
    postalCode: 'V6V 1Z9',
  },
  {
    regNo: 4437,
    name: 'KIKUMBIA PHARMACEUTICALS LTD.',
    adba: 'THE VILLAGE CHEESE COMPANY',
    telephone: '(250) 546-8651',
    streetAddr: '3475 SMITH DRIVE',
    city: 'ARMSTRONG',
    province: 'BC',
    postalCode: 'V0E 1B1',
  },
  {
    regNo: 4438,
    name: 'PUNJAB MILK FOODS INC.',
    adba: 'BRAND: NANAK',
    telephone: '(604) 594-9190',
    streetAddr: '200 - 14666 64th Avenue',
    city: 'SURREY',
    province: 'BC',
    postalCode: 'V3S 1X7',
  },
  {
    regNo: 4439,
    name: 'Meadowfresh Dairy Corporation',
    adba: null,
    telephone: '(604) 472-0786',
    streetAddr: '1373 Kebet Way',
    city: 'PORT COQUITLAM',
    province: 'BC',
    postalCode: 'V3C 6G1',
  },
  {
    regNo: 4440,
    name: 'LASTELLA FOODS MANUFACTURING LTD.',
    adba: null,
    telephone: '(604) 327-2434',
    streetAddr: '7028 MERRITT AVENUE',
    city: 'BURNABY',
    province: 'BC',
    postalCode: 'V5J 4R6',
  },
  {
    regNo: 4441,
    name: 'AVALON DAIRY LIMITED',
    adba: null,
    telephone: '(604) 456-0550',
    streetAddr: '7985 North Fraser Way',
    city: 'BURNABY',
    province: 'BC',
    postalCode: 'V5J 0A4',
  },
  {
    regNo: 4442,
    name: 'EFCON IMPORTS INC.',
    adba: 'EFCON INC.',
    telephone: '(604) 941-6628',
    streetAddr: '113 1551 BROADWAY STREET',
    city: 'PORT COQUITLAM',
    province: 'BC',
    postalCode: 'V3C 3N9',
  },
  {
    regNo: 4443,
    name: 'SALT SPRING ISLAND CHEESE CO.',
    adba: null,
    telephone: '(250) 653-2300',
    streetAddr: '285 REYNOLDS ROAD',
    city: 'SALT SPRING ISLAND',
    province: 'BC',
    postalCode: 'V8K 1Y2',
  },
  {
    regNo: 4445,
    name: '0901262 B.C. Ltd.',
    adba: 'Upper Bench Estate Winery',
    telephone: '(250) 770-1733',
    streetAddr: '170 Upper Bench Road South',
    city: 'PENTICTON',
    province: 'BC',
    postalCode: 'V2A 8T1',
  },
  {
    regNo: 4446,
    name: 'Pacific Blends Ltd.',
    adba: null,
    telephone: '(604) 945-4600',
    streetAddr: '#100-1625 Kebet Way',
    city: 'Coquitlam',
    province: 'BC',
    postalCode: 'V3C 5W9',
  },
  {
    regNo: 4451,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(604) 444-7215',
    streetAddr: '6800 LOUGHEED HIGHWAY',
    city: 'BURNABY',
    province: 'BC',
    postalCode: 'V5A 1W2',
  },
  {
    regNo: 4459,
    name: 'MOUNTAIN VALLEY DAIRY LTD.',
    adba: 'KOOTENAY MEADOWS',
    telephone: '(250) 428-9655',
    streetAddr: '3071 16TH STREET',
    city: 'Creston',
    province: 'BC',
    postalCode: 'V0B 1G2',
  },
  {
    regNo: 4465,
    name: 'FLAMINGO FOODS LTD.',
    adba: 'SCARDILLO CHEESE',
    telephone: '(604) 209-8018',
    streetAddr: '7865 VENTURE STREET',
    city: 'BURNABY',
    province: 'BC',
    postalCode: 'V5A 1V1',
  },
  {
    regNo: 4466,
    name: 'POPLAR GROVE CHEESE INC.',
    adba: null,
    telephone: '(250) 492-2352',
    streetAddr: '1060 POPLAR GROVE ROAD',
    city: 'PENTICTON',
    province: 'BC',
    postalCode: 'V2A 8T6',
  },
  {
    regNo: 4468,
    name: 'Agropur Cooperative',
    adba: null,
    telephone: '(604) 527-4491',
    streetAddr: '7650 18TH STREET',
    city: 'BURNABY',
    province: 'BC',
    postalCode: 'V3N 4K3',
  },
  {
    regNo: 4469,
    name: "MARIO'S GELATI LTD.",
    adba: null,
    telephone: '(604) 879-9411',
    streetAddr: '88 EAST FIRST AVENUE',
    city: 'VANCOUVER',
    province: 'BC',
    postalCode: 'V5T 1A1',
  },
  {
    regNo: 4470,
    name: 'HAPPY DAYS DAIRIES LTD.',
    adba: null,
    telephone: '(604) 823-5541',
    streetAddr: '7350 A BARROW ROAD',
    city: 'CHILLIWACK',
    province: 'BC',
    postalCode: 'V2R 4J8',
  },
  {
    regNo: 4474,
    name: 'Saputo Dairy Products Canada G.P.',
    adba: null,
    telephone: '(604) 853-2225',
    streetAddr: '1799 RIVERSIDE DRIVE',
    city: 'ABBOTSFORD',
    province: 'BC',
    postalCode: 'V2S 4J8',
  },
  {
    regNo: 4476,
    name: 'HAPPY DAYS DAIRIES LTD.',
    adba: null,
    telephone: '(250) 832-0209',
    streetAddr: '691 SALMON RIVER ROAD',
    city: 'SALMON ARM',
    province: 'BC',
    postalCode: 'V1E 3E9',
  },
  {
    regNo: 4477,
    name: 'PARADISE ISLAND FOODS INC.',
    adba: null,
    telephone: '(250) 390-2644',
    streetAddr: '6451 PORTSMOUTH ROAD',
    city: 'NANAIMO',
    province: 'BC',
    postalCode: 'V9V 1A3',
  },
  {
    regNo: 4478,
    name: 'KATHY WIKKERINK, GARY WIKKERINK',
    adba: 'Grass Root Dairies',
    telephone: '(250) 832-4274',
    streetAddr: '1470 - 50th Street S.W.',
    city: 'SALMON ARM',
    province: 'BC',
    postalCode: 'V1E 3B5',
  },
  {
    regNo: 4479,
    name: 'GFR Pharma Ltd.',
    adba: null,
    telephone: '(604) 460-8440',
    streetAddr: '65 North Bend Street',
    city: 'Coquitlam',
    province: 'BC',
    postalCode: 'V3K 6N9',
  },
  {
    regNo: 4480,
    name: 'Prabu Foods Inc.',
    adba: null,
    telephone: '(604) 283-1551',
    streetAddr: '8035 130th Street',
    city: 'Surrey',
    province: 'BC',
    postalCode: 'V3W 7X4',
  },
  {
    regNo: 4481,
    name: 'CANADIAN CULTURED DAIRY INC.',
    adba: 'TREE ISLAND GOURMET YOGURT',
    telephone: '(250) 334-0608',
    streetAddr: '3747 ISLAND HIGHWAY SOUTH',
    city: 'COURTENAY',
    province: 'BC',
    postalCode: 'V9N 9T4',
  },
  {
    regNo: 4605,
    name: 'AGROPUR COOPERATIVE',
    adba: 'CENTRAL DAIRIES DIVISION/NATREL',
    telephone: '(709) 364-1172',
    streetAddr: "12 BRUCE STREET, Donovan's Industrual Park",
    city: 'Mount Pearl',
    province: 'NL',
    postalCode: 'A1N 4T4',
  },
]
